// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebinsabu13/microservice_video_streaming/video_service/pkg/Repository"
	"github.com/stebinsabu13/microservice_video_streaming/video_service/pkg/api"
	"github.com/stebinsabu13/microservice_video_streaming/video_service/pkg/api/service"
	"github.com/stebinsabu13/microservice_video_streaming/video_service/pkg/config"
	"github.com/stebinsabu13/microservice_video_streaming/video_service/pkg/db"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	videoRepo := repository.NewVideoRepo(gormDB)
	videoServiceServer := service.NewVideoServer(videoRepo)
	server, err := api.NewgrpcServe(c, videoServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
